#!/usr/bin/env bash

NEWBRIGHT=2000

NEWBRIGHT=$(cat /sys/class/backlight/intel_backlight/brightness)

MAXBRIGHT=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [ "$1" = "inc" ]; then
	NEWBRIGHT=$((NEWBRIGHT+$2))
elif [ "$1" = "dec" ]; then
	NEWBRIGHT=$((NEWBRIGHT-$2))
elif [ "$1" = "set" ]; then
	NEWBRIGHT=$2
fi

if [ $NEWBRIGHT -gt $MAXBRIGHT ]; then
	NEWBRIGHT = $MAXBRIGHT
fi

echo $NEWBRIGHT | sudo tee /sys/class/backlight/intel_backlight/brightness
