#!/usr/bin/env bash

if (setxkbmap -query | grep -q "layout:\s\+gb"); then
    setxkbmap de qwerty
elif (setxkbmap -query | grep -q "layout:\s\+de"); then
    echo "to ru"
    setxkbmap ru
else
    setxkbmap gb
fi
